# Generated by Django 6.0 on 2025-12-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('present_address_line1', models.CharField(max_length=255)),
                ('present_address_line2', models.CharField(blank=True, max_length=255)),
                ('present_city', models.CharField(max_length=255)),
                ('present_state', models.CharField(max_length=100)),
                ('present_pincode', models.CharField(max_length=10)),
                ('present_country', models.CharField(default='India', max_length=100)),
                ('permanent_address_same_as_present', models.BooleanField(default=False)),
                ('permanent_address_line1', models.CharField(blank=True, max_length=255)),
                ('permanent_address_line2', models.CharField(blank=True, max_length=255)),
                ('permanent_city', models.CharField(blank=True, max_length=100)),
                ('permanent_state', models.CharField(blank=True, max_length=100)),
                ('permanent_pincode', models.CharField(blank=True, max_length=10)),
                ('permanent_country', models.CharField(blank=True, max_length=100)),
                ('name_gender_proof', models.FileField(upload_to='name_gender_proof/')),
                ('dob_proof', models.FileField(upload_to='dob_proofs/')),
                ('address_proof', models.FileField(upload_to='address_proofs/')),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('verification_results', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
