# Generated by Django 6.0 on 2025-12-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify_user', '0002_emailotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passportrecord',
            name='permanent_address_line1',
        ),
        migrations.RemoveField(
            model_name='passportrecord',
            name='permanent_address_line2',
        ),
        migrations.RemoveField(
            model_name='passportrecord',
            name='present_address_line1',
        ),
        migrations.RemoveField(
            model_name='passportrecord',
            name='present_address_line2',
        ),
        migrations.AddField(
            model_name='passportrecord',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='passportrecord',
            name='present_address',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
