# Generated by Django 6.0 on 2025-12-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify_user', '0003_remove_passportrecord_permanent_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportrecord',
            name='staus',
            field=models.CharField(blank=True, choices=[('PENDING', 'pending'), ('VERIFIED', 'verified')], max_length=10),
        ),
    ]
