# Generated by Django 6.0 on 2025-12-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify_user', '0004_passportrecord_staus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passportrecord',
            name='staus',
        ),
        migrations.AddField(
            model_name='passportrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('VERIFIED', 'verified')], default='PENDING', max_length=10),
        ),
    ]
