# Generated by Django 6.0 on 2025-12-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify_user', '0005_remove_passportrecord_staus_passportrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportrecord',
            name='dob_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passportrecord',
            name='email_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passportrecord',
            name='first_name_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passportrecord',
            name='gender_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passportrecord',
            name='last_name_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passportrecord',
            name='middle_name_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passportrecord',
            name='permanent_address_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passportrecord',
            name='permanent_city_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passportrecord',
            name='permanent_country_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passportrecord',
            name='permanent_pincode_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passportrecord',
            name='permanent_state_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passportrecord',
            name='phone_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passportrecord',
            name='present_address_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passportrecord',
            name='present_city_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passportrecord',
            name='present_country_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passportrecord',
            name='present_pincode_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passportrecord',
            name='present_state_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
