# Generated by Django 6.0 on 2025-12-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verify_user', '0005_remove_passportrecord_staus_passportrecord_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passportrecord',
            old_name='permanent_address',
            new_name='permanent_address_line',
        ),
    ]
