# Generated by Django 6.0 on 2025-12-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verify_user', '0006_rename_permanent_address_passportrecord_permanent_address_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passportrecord',
            old_name='present_address',
            new_name='present_address_line',
        ),
    ]
